### ISSUE TITLE
Relax smart-open dependency version

### ISSUE THREAD

**Issue by mmcfarland** [stac-utils/pgstac#273]
In the [Rust Hydration PR](https://github.com/stac-utils/pgstac/pull/201/commits/d3c7a82eca97589d9318bd0f2ffd4d071bf4ae1a#diff-cee320e6419458b93fa030d9de35a37a922cedf8940966f1c3abb4dabea79add) smart-open went from `>=4.2,<7.0",` to `==6.3.*`. Is this hard pin necessary? 

In our specific case, we're looking to use smart-open 6.4, which the old range would have satisfied.

https://github.com/piskvorky/smart_open/releases/tag/v6.4.0

**Comment by bitner** [comment]
Hmm, not sure why I made that change. I think it was unintentional. I'll test and update.

**Comment by mmcfarland** [comment]
Thanks @bitner! I don't recall how easy it is to backport changes to releases, but if it's good, could it be made to a `0.8.6` as well as whatever is next for `0.9` (which isn't yet compatible with the latest stac-fastapi.* series)?

**Comment by bitner** [comment]
Right now we have a hard coded setting that pypgstac needs to be on the same major version as the pgstac that it is working with. The other option is to relax that a bit and allow ranges of pgstac versions that pypgstac can work with so that we could use pypgstac 0.9.1 to work with pgstac 0.8.5.

**Comment by mmcfarland** [comment]
I think the main challenge is having an option to avoid the breaking changes in 0.9 for now. If we can't get something on the 0.8.x branch probably it's just good enough to know that there's isn't a hard requirement for smart-open and we can just force the dependency version we want somehow.

**Comment by zstatmanweil** [comment]
hey @bitner, I am on 0.9.0 and am awaiting this change as having a hard time forcing the install with my org's current setup. Any idea when 0.9.1 may be released? If it isn't for a while and it isn't too much work, any chance you would be wiling to cut a release of 0.9.1 with this change?

**Comment by bitner** [comment]
@zstatmanweil I can cut a 0.9.1, I've got a couple other fixes to get in a release, I'll try to kick out a new release by end of tomorrow.

**Comment by zstatmanweil** [comment]
Amazing! Thank you so much :)

**Comment by zstatmanweil** [comment]
Hey @bitner, just following up on this. Do you think a new release still coming soon? Otherwise I am going to have to get creative with my solution :). Thanks!

**Comment by vincentsarago** [comment]
Hi @zstatmanweil 
David is off this week so I think the release will only happen next week.

Can installing from GitHub source work for you ?

**Comment by zstatmanweil** [comment]
Hi @vincentsarago , I can if necessary. I will see if it is released this week and then do that. Thanks!

**Comment by bitner** [comment]
Sorry @zstatmanweil ! I meant to get things released before going on vacation last week, but things got busy as always. I've just pushed a release to v0.9.1 that has this fix in it.

**Comment by zstatmanweil** [comment]
@bitner I understand of course! Thanks so much :) I really appreciate it.

**Comment by zstatmanweil** [comment]
hey @bitner , should I be seeing it as a release? Or is there an additional process behind the scenes? I still see 0.8.6 as the latest

**Comment by bitner** [comment]
@zstatmanweil I'm seeing it now. It may have taken CI a bit to run to make the release.

**Comment by zstatmanweil** [comment]
@bitner thanks! It does look like one of the linux builds failed so it never made it to pypi.

**Comment by bitner** [comment]
Uggh. Don't know what bombed on that run, but when I just kicked those jobs in CI off again, everything went through fine and I'm seeing 0.9.1 up on pypi now. Sorry again for all the rigmarole @zstatmanweil I *think* that everything should be good to go now <cross-fingers/>
